---
title: "R Notebook"
output: html_notebook
---

---
output:
  html_document: default
  word_document: default
---





# set up

## libraries


```{r libraries}
library(tidyverse)

library(diptest)

library("car")
```


## download data

```{r upload and merge data sets}
gunda_plots_csv <- read_csv("Gunda_copy_data/gunda_plots_csv/Gunda_csv/gunda_plots_csv.csv")
```



# biomass calculations

## calculate total diamiter

```{r calculate total diamiter for site}

gunda_basal_area <- gunda_plots_csv %>%
  gather("d_10", "diamiter", 2:11)%>%
  mutate(basal_area = (diamiter*0.5)^2*3.14159265359)

#combind basal area for multi stemmed trees 
gunda_Total_basal_area <- aggregate(basal_area~tree+landform,gunda_basal_area,sum)

#back tranform total_basal_area to diamiter 
gunda_total_diam <- mutate(gunda_Total_basal_area, Total_d = (sqrt(basal_area/3.14159265359))*2)

#extract the total_diamiter measurments and bind to original data set
diam_gunda_sites <- left_join(gunda_plots_csv,gunda_total_diam, by = c("tree", "landform"))

#plot damiter measurements 

#diamiter
diam_gunda_sites%>%
ggplot( aes(x=Total_d, colour = factor(landform))) +
  geom_histogram( fill = "#69b3a2",
                  alpha = 0.09,
                  bins = 40)+
  ggtitle("Individual diamiters")+
  theme_classic()+
  theme(plot.title = element_text(size = 15))
```

## calculate biomass using diamiter calculations 

```{r log Biomass estimates Gunda booka Paul and Roxburgh}


# Equations taken from -> Paul et al, "testing the generality of above ground biomass allometry across plant funcitoal types at the continent scale"

# First equation -> Universal eaution "ln(AGB) = 2.503ln(D10)-3.024" based on D10 (page 9)

gunda_biomass <- mutate(diam_gunda_sites,
                        log_AGB = 2.503*log(Total_d)-3.024, 
                        AGB = exp(log_AGB),
                        log_AGB_williams = -2.0596 + 2.1561*(log(Total_d) + 0.1362*(log(height/100))^2))

#plot the ln(AGB) dist

#Universal plot
gunda_biomass%>%
ggplot( aes(x=AGB, colour = factor(landform))) +
  geom_histogram( fill = "#69b3a2",
                  alpha = 0.09,
                  bins = 40)+
  scale_x_log10()+
  ggtitle("biomass")+
  theme_classic()+
  theme(plot.title = element_text(size = 15))
```

# normality check 

used qq-plots and shapiro wilk test 
```{r}
qqnorm(gunda_biomass$log_AGB, pch = 1, frame = FALSE)
qqline(gunda_biomass$log_AGB, col = "steelblue", lwd = 2)
qqPlot(gunda_biomass$log_AGB)

shapiro.test(gunda_biomass$log_AGB)
```

## diptest


```{r Hatigan's dip test for williams biomass dist}
dip.test(gunda_biomass$log_AGB)
dip(gunda_biomass$log_AGB, full.result = TRUE, min.is.0 = FALSE, debug = FALSE)
```





# plot biomass 

```{r aggregate biomass for each plot and landform }
gunda_plot_biomass <- aggregate(AGB ~ plots + landform, gunda_biomass, sum)

gunda_area <- aggregate(area_m2 ~ plots + landform, gunda_biomass, mean)

g.biomass.area <- left_join(gunda_plot_biomass, gunda_area, by = c("plots", "landform"))

g.biom.meter <- mutate( g.biomass.area, bio.m = AGB/area_m2)

```



```{r}
plot(g.biom.meter$bio.m)
```