---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(diptest)
library("car")
library(reader)
```

## uploda data 

```{r upload data sets}
noco_plots_csv <- read_csv("plot_data/noco_plots.csv.csv")
View(noco_plots_csv)
```
# calculate biomass

## find total diamiter

```{r}

noco_basal_area <- noco_plots_csv %>%
  gather("d_10", "diamiter", 2:11)%>%
  mutate(basal_area = (diamiter*0.5)^2*3.14159265359)

#combind basal area for multi stemmed trees 
noco_Total_basal_area <- aggregate(basal_area~tree+landform,noco_basal_area,sum)

#back tranform total_basal_area to diamiter 
noco_total_diam <- mutate(noco_Total_basal_area, Total_d = (sqrt(basal_area/3.14159265359))*2)

#extract the total_diamiter measurments and bind to original data set

diam_noco_sites <- left_join(noco_plots_csv,noco_total_diam, by = c("tree", "landform"))

#plot damiter measurements 

#diamiter
diam_noco_sites%>%
ggplot( aes(x=noco_total_diam$Total_d, colour = factor(landform))) +
  geom_histogram( fill = "#69b3a2",
                  alpha = 0.09,
                  bins = 40)+
  ggtitle("Individual diamiters")+
  theme_classic()+
  theme(plot.title = element_text(size = 15))

```


```{r}

# Equations taken from -> Paul et al, "testing the generality of above ground biomass allometry across plant funcitoal types at the continent scale"

#Second equation -> Fmulti "ln(AGB) = 2.474ln(D10)-2.757" (page 9)

noco_multi_stem <- mutate(diam_noco_sites,
                          logAGB = 2.474*log(noco_total_diam$Total_d)-2.757,
                          AGB = exp(logAGB))

filtered_noco_biomass <- filter(noco_multi_stem,
                                logAGB > 1, 
                                AGB > 2.72)

#plot the ln(AGB) dist

#multi_stem plot
filtered_noco_biomass%>%
ggplot( aes(x=AGB, colour = factor(landform))) +
  geom_histogram( fill = "#69b3a2",
                  alpha = 0.09,
                  bins = 40)+
  scale_x_log10()+
  ggtitle("multistem logAGB")+
  theme_classic()+
  theme(plot.title = element_text(size = 15))
```

# check for normality 

```{r}


filtered_noco_biomass$logAGB
qqnorm(filtered_noco_biomass$logAGB, pch = 1, frame = FALSE)
qqline(filtered_noco_biomass$logAGB, col = "steelblue", lwd = 2)
qqPlot(filtered_noco_biomass$logAGB)

shapiro.test(filtered_noco_biomass$logAGB )
```

# biomass per m^2 

```{r}
noco_plot_biomass <- aggregate(AGB ~ plots + landform,filtered_noco_biomass, sum)

noco_area <- aggregate(area_m2 ~ plots + landform, filtered_noco_biomass, mean)

n.biomass.area <- left_join(noco_plot_biomass, noco_area, by = c("plots", "landform"))

n.biom.meter <- mutate( n.biomass.area, bio.m = AGB/area_m2)

```

```{r}
plot(n.biom.meter$bio.m)
```
