---
title: "R Notebook"
output: html_notebook
---



```{r libraries}
library(tidyverse)
library(diptest)
library("car")
```

## import and set up data
```{r upload data_set}
sturt_plots_csv <- read_csv("plot_data/sturt_plots.csv.csv")
View(sturt_plots_csv)
```

# calculate biomass 

## find total diamiter

```{r calculate total diamiter for the sturt}
sturt_basal_area <- sturt_plots_csv %>%
  gather("d_10", "diamiter", 2:11)%>%
  mutate(basal_area = (diamiter*0.5)^2*3.14159265359)

#combind basal area for multi stemmed trees 
sturt_Total_basal_area <- aggregate(basal_area~tree+landform,sturt_basal_area,sum)

#back tranform total_basal_area to diamiter 
sturt_total_diam <- mutate(sturt_Total_basal_area, Total_d = (sqrt(basal_area/3.14159265359))*2)

#extract the total_diamiter measurments and bind to original data set
diam_sturt_sites <-left_join(sturt_plots_csv,sturt_total_diam, by = c("tree", "landform"))

#plot damiter measurements 

#diamiter
diam_sturt_sites%>%
ggplot( aes(x=sturt_total_diam$Total_d, colour = factor(landform))) +
  geom_histogram( fill = "#69b3a2",
                  alpha = 0.09,
                  bins = 40)+
  ggtitle("Individual diamiters")+
  theme_classic()+
  theme(plot.title = element_text(size = 15))
```


#paul and roxbrough biomass equations
```{r}

# Equations taken from -> Paul et al, "testing the generality of above ground biomass allometry across plant funcitoal types at the continent scale"

# Second equation -> Fmulti "ln(AGB) = 2.474ln(D10)-2.757" (page 9)

sturt_biomass <- mutate(diam_sturt_sites,
                           logAGB = 2.474*log(Total_d)-2.757,
                           AGB = exp(logAGB))

#plot the biomass dist

#multistem

sturt_biomass%>%
ggplot( aes(x=AGB, colour = factor(landform))) +
  geom_histogram( fill = "#69b3a2",
                  alpha = 0.09,
                  bins = 40)+
  scale_x_log10()+
  ggtitle("multi stem biomass")+
  theme_classic()+
  theme(plot.title = element_text(size = 15))
```

```{r}

sturt_biomass$logAGB
qqnorm(sturt_biomass$logAGB, pch = 1, frame = FALSE)
qqline(sturt_biomass$logAGB, col = "steelblue", lwd = 2)
qqPlot(sturt_biomass$logAGB)

shapiro.test(sturt_biomass$logAGB)
```

```{r Hatigan's dip test for williams biomass dist}

dip.test(sturt_biomass$logAGB)
dip(sturt_biomass$logAGB, full.result = TRUE, min.is.0 = FALSE, debug = FALSE)
```

```{r}

g.biom.meter %>% 
  ggplot(aes(x = bio.m, colour = factor(landform)))+
  geom_histogram()+
  ggtitle("subplot biomass")+
  xlab("biomass/m^2")
```

## noco subplot biomass

### calculate biomass per m2

#biomass per m^2 

```{r aggregate biomass for each plot and landform }

sturt_plot_biomass <- aggregate(AGB ~ plots + landform, sturt_biomass, sum)

sturt_area <- aggregate(area_m2 ~ plots + landform, sturt_biomass, mean)

s.biomass.area <- left_join(sturt_plot_biomass, sturt_area, by = c("plots", "landform"))

s.biom.meter <- mutate( s.biomass.area, bio.m = AGB/area_m2)

print(s.biom.meter)
```

```{r}

plot(s.biom.meter$bio.m)
```



